theme: jekyll-theme-minimal
google_site_verification : Oy9sum8vz_1KL6_GhCVYGyWyRO1Npfh8RzVxhk-OeTs
title: PhotoDedupe
description : A command line utility for locating duplicate photos irrespective of image resolution, compression settings or file format.
tagline: A utility for locating duplicate photos
keywords: "photodedupe,images,photos,duplicates,deduplication,de-duplication,visual,similar,similarity"
